Description: A Lambda function to auto subscribe Axiom CloudWatch Forwarder to new log groups.
Parameters:
  AxiomCloudWatchForwarderLambdaARN:
    Type: String
    Description: The ARN of the AWS Lambda function that is used to forward logs to Axiom.
    AllowedPattern: ".+" # required
  CloudWatchLogGroupsPrefix:
    Type: String
    Description: The prefix of the CloudWatch log groups that will trigger the Axiom CloudWatch Forwarder Lambda.
    Default: "" # all
  AxiomLambdaLogRetention:
    Type: "Number"
    Description: "The number of days to retain CloudWatch logs for the created Lambda functions."
    Default: 1
Resources:
  ListenerEventRule:
    DependsOn: ListenerLambda
    Type: AWS::Events::Rule
    Properties:
      Description: Axiom log group auto subscription event rule.
      EventPattern:
        source: ["aws.logs"]
        detail-type: ["AWS API Call via CloudTrail"]
        detail:
          eventSource: ["logs.amazonaws.com"]
          eventName: ["CreateLogGroup"]
      Name:
        "Fn::Join":
          ["-", [{ "Ref": "AWS::StackName" }, "auto-subscription-rule"]]
      Targets:
        - Id: !Join ["-", [!Ref "AWS::StackName", "auto-subscription-rule"]]
          Arn: !GetAtt ["ListenerLambda", "Arn"]
  ListenerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:DeleteSubscriptionFilter
              - logs:PutSubscriptionFilter
              - logs:DescribeLogGroups
              - lambda:AddPermission
              - lambda:RemovePermission
              - lambda:InvokeFunction
              - lambda:GetFunction
              - logs:DescribeLogStreams
              - logs:DescribeSubscriptionFilters
              - logs:FilterLogEvents
              - logs:GetLogEvents
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: "*"
      PolicyName: axiom-cloudwatch-listener-policy
      Roles:
        - !Ref "ListenerRole"
  ListenerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - logs.amazonaws.com
  ListenerLambda:
    Type: AWS::Lambda::Function
    DependsOn:
      - ListenerRole
    Properties:
      FunctionName: !Sub "${AWS::StackName}"
      Runtime: python3.9
      Handler: index.lambda_handler
      Code:
        S3Bucket: "# CI will replace these comments with the code from src/listener.py"
        S3Key: ""
      Role: !GetAtt
        - ListenerRole
        - Arn
      Description: Axiom CloudWatch Automatic log groups listener lambda
      Environment:
        Variables:
          AXIOM_CLOUDWATCH_FORWARDER_LAMBDA_ARN: !Ref "AxiomCloudWatchForwarderLambdaARN"
          LOG_GROUP_PREFIX: !Ref "CloudWatchLogGroupsPrefix"
  ListenerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: { "Fn::GetAtt": ["ListenerLambda", "Arn"] }
      Principal: "events.amazonaws.com"
      SourceAccount:
        Ref: AWS::AccountId
      SourceArn: !GetAtt ["ListenerEventRule", "Arn"]
  ListenerLogGroup:
    DependsOn: ["ListenerRole"]
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/axiom/${AWS::StackName}"
      RetentionInDays:
        Ref: "AxiomLambdaLogRetention"
