Description: A lambda that creates subscription filters for existing log groups
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Forwarder lambda"
        Parameters:
          - AxiomCloudWatchForwarderLambdaARN
      - Label:
          default: "Which log groups to subscribe to?"
        Parameters:
          - CloudWatchLogGroupsNames
          - CloudWatchLogGroupsPrefix
          - CloudWatchLogGroupsPattern

Parameters:
  AxiomCloudWatchForwarderLambdaARN:
    Type: String
    Description: The ARN of the Axiom CloudWatch Forwarder Lambda function used to ship logs to Axiom.
    AllowedPattern: ".+" # required
  CloudWatchLogGroupNames:
    Type: String
    Description: A comma separated list of CloudWatch log groups to subscribe to.
    Default: "" # all
  CloudWatchLogGroupPrefix:
    Type: String
    Description: The Prefix of CloudWatch log groups to subscribe to.
    Default: "" # all
  CloudWatchLogGroupPattern:
    Type: String
    Description: A regular expression pattern of CloudWatch log groups to subscribe to.
    Default: "" # all
  ForceUpdate:
    Type: String
    Description: Enter a random string to force an update of the stack.
    Default: ""
Resources:
  SubscriberPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:DescribeSubscriptionFilters
              - logs:DeleteSubscriptionFilter
              - logs:PutSubscriptionFilter
              - logs:DescribeLogGroups
              - logs:CreateLogStream
              - logs:PutLogEvents
              - lambda:AddPermission
              - lambda:RemovePermission
            Effect: Allow
            Resource: "*"
      PolicyName: !Sub "${AWS::StackName}-subscriber-lambda-policy"
      Roles:
        - !Ref "SubscriberRole"
  SubscriberLogGroup:
    Type: "AWS::Logs::LogGroup"
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/axiom/${AWS::StackName}"
      RetentionInDays: 1
      Tags:
        - Key: "PartOf"
          Value: !Ref AWS::StackName
        - Key: "Platform"
          Value: "Axiom"
        - Key: "Role"
          Value: "AxiomCloudWatchSubscriber"
  SubscriberRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
  SubscriberLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}"
      Runtime: python3.9
      Handler: index.lambda_handler
      Timeout: 300
      Code:
        ZipFile: |
          # DO NOT EDIT
          # CI will replace these comments with the code from ./subscriber.py
      Role: !GetAtt
        - SubscriberRole
        - Arn
      LoggingConfig:
        LogGroup: !Ref SubscriberLogGroup
      Tags:
        - Key: "PartOf"
          Value: !Ref AWS::StackName
        - Key: "Role"
          Value: "AxiomCloudWatchSubscriber"
        - Key: "Platform"
          Value: "Axiom"
        - Key: "ForwarderARN"
          Value: !Ref "AxiomCloudWatchForwarderLambdaARN"
      Environment:
        Variables:
          AXIOM_CLOUDWATCH_FORWARDER_LAMBDA_ARN: !Ref "AxiomCloudWatchForwarderLambdaARN"
  SubscriberInvoker:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: SubscriberLambda
    Version: "1.0"
    Properties:
      ServiceToken: !GetAtt SubscriberLambda.Arn
      StackName: !Ref AWS::StackName
      Force: !Ref "ForceUpdate"
      CloudWatchLogGroupNames: !Ref "CloudWatchLogGroupNames"
      CloudWatchLogGroupPrefix: !Ref "CloudWatchLogGroupPrefix"
      CloudWatchLogGroupPattern: !Ref "CloudWatchLogGroupPattern"
