Description: A lambda that removes subscription filters for provided log groups
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Forwarder lambda"
        Parameters:
          - AxiomCloudWatchForwarderLambdaARN
      - Label:
          default: "Log groups to unsubscribe from"
        Parameters:
          - CloudWatchLogGroupsNames
          - CloudWatchLogGroupsPrefix
          - CloudWatchLogGroupsPattern

Parameters:
  AxiomCloudWatchForwarderLambdaARN:
    Type: String
    Description: The ARN of the Axiom CloudWatch Forwarder Lambda function used to forward logs to Axiom.
    AllowedPattern: ".+" # required
  CloudWatchLogGroupNames:
    Type: String
    Description: A comma-separated list of CloudWatch log groups to unsubscribe from.
    Default: "" # all
  CloudWatchLogGroupPrefix:
    Type: String
    Description: The prefix of CloudWatch log groups to unsubscribe from.
    Default: "" # all
  CloudWatchLogGroupPattern:
    Type: String
    Description: A regular expression pattern for CloudWatch log groups to unsubscribe from.
    Default: "" # all
  ForceUpdate:
    Type: String
    Description: Enter a random string to force an update of the stack.
    Default: ""
Resources:
  UnsubscriberPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:DescribeSubscriptionFilters
              - logs:DeleteSubscriptionFilter
              - logs:PutSubscriptionFilter
              - logs:DescribeLogGroups
              - logs:CreateLogStream
              - logs:PutLogEvents
              - lambda:AddPermission
              - lambda:RemovePermission
            Effect: Allow
            Resource: "*"
      PolicyName: !Sub "${AWS::StackName}-unsubscriber-lambda-policy"
      Roles:
        - !Ref "UnsubscriberRole"
  UnsubscriberLogGroup:
    Type: "AWS::Logs::LogGroup"
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/axiom/${AWS::StackName}"
      RetentionInDays: 1
      Tags:
        - Key: "PartOf"
          Value: !Ref AWS::StackName
        - Key: "Role"
          Value: "AxiomCloudWatchUnsubscriber"
        - Key: "Platform"
          Value: "Axiom"
  UnsubscriberRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
  UnsubscriberLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}"
      Runtime: python3.9
      Handler: index.lambda_handler
      Timeout: 300
      Code:
        ZipFile: |
          # DO NOT EDIT
          # CI will replace these comments with the code from ./unsubscriber.py
      Role: !GetAtt
        - UnsubscriberRole
        - Arn
      LoggingConfig:
        LogGroup: !Ref UnsubscriberLogGroup
      Tags:
        - Key: "PartOf"
          Value: !Ref AWS::StackName
        - Key: "Role"
          Value: "AxiomCloudWatchUnsubscriber"
        - Key: "Platform"
          Value: "Axiom"
      Environment:
        Variables:
          AXIOM_CLOUDWATCH_FORWARDER_LAMBDA_ARN: !Ref "AxiomCloudWatchForwarderLambdaARN"
  UnsubscriberInvoker:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: UnsubscriberLambda
    Version: "1.0"
    Properties:
      ServiceToken: !GetAtt UnsubscriberLambda.Arn
      StackName: !Ref AWS::StackName
      Force: !Ref "ForceUpdate"
      CloudWatchLogGroupNames: !Ref "CloudWatchLogGroupNames"
      CloudWatchLogGroupPrefix: !Ref "CloudWatchLogGroupPrefix"
      CloudWatchLogGroupPattern: !Ref "CloudWatchLogGroupPattern"
